# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Smart Contract Tips
email: team@smartcontract.tips
description: >- # this means to ignore newlines until "baseurl:"
  Questo sito promuove la cultura della sicurezza informatica nel web3.
  This website advocates the practices of secure coding in web3.
  Donate-to 0x850521064b85587C376B709deA1687ae8f3F8640 on any EVM chain  ❤️ 🙏.  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://smartcontract.tips" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: digitaldavide
github_username:  ddbit

# this is my personal hack on category flag
enable_categories: false


# Build settings
theme: minima
#remote_theme: jekyll/minima
markdown: kramdown

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap



landing_path: landing

language_default: it

collections_dir: content
collections:
  articoli:
    output: true 
    permalink: /:collection/:permalink
  it:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug
  authors:
    people: true
    output: true 
    permalink: /:collection/:slug
  lezioni_crittografia:
    output: true 
    permalink: /:collection/:slug


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: ""
  -
    scope:
      path: ""
      type: "it"
    values:
      layout: "page"
  -
    scope:
      path: "_it/posts"
    values:
      layout: "post"
      permalink: /it/post/:slug
  -
    scope:
      path: ""
      type: "en"
    values:
      layout: "page"
  -
    scope:
      path: "_en/posts"
    values:
      layout: "post"
      permalink: /en/post/:slug



## section for related.html

related_by: tags      # Match on both categories and tags
related_limit: 5      # Include 5 related pages
related_tags: 1       # Match with at least 1 tags.

## end of related section


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
